### ISSUE TITLE
USER STORY: Colour scheme selection

### ISSUE THREAD

**Issue by GaryDolan** [GaryDolan/ci-p4-happy-little-artists#1]
As a **developer** I can **select a colour scheme** so that **the websites colouring creates a positive user experience and also meets the stakeholders aesthetic goals**. 

# Acceptance Criteria: 
1. The primary and supporting colours have been selected and align with the stakeholders branding goals for the website.
2. All colour combinations pass accessibility standards providing sufficient contrast and readability.
3. Colour pallet is cohesive and aesthetically pleasing.
4. Image of colour scheme has been saved for use in the README file.

# Tasks:
- [x] Carry out meeting with the stakeholder (my wife Amanda) and discuss her initial ideas regarding colour scheme.
- [x] Carry out investigations of possible colour schemes using other websites and colour palette generators.
- [x] Decide on the websites primary colours, call to action colour and supporting colours. 
- [x] Use WebAIM to test the selected colour combinations and make adjustments where necessary to comply with all standards.
- [x] Review colour scheme with stakeholder to ensure it aligns with her branding for the website.  
- [x] Use coolors.co to create an image of colour scheme and save for later use.

**Comment by GaryDolan** [comment]
Colour scheme has been finalised.
