### ISSUE TITLE
USER STORY: Initial Heroku deployment

### ISSUE THREAD

**Issue by GaryDolan** [GaryDolan/ci-p4-happy-little-artists#10]
As a **Developer** I can **deploy my project to Heroku** so that **I can confirm correct operation early in the project**.

# Acceptance Criteria: 
1. Deployment completes with no issues.
2. Open App button from Heroku dashboard shows success page.

# Tasks:
- [x] Create a new Heroku app happy-little-artists
- [x] Add DATABASE_URL,  SECRET_KEY, CLOUDINARY_URL and PORT (8000) config vars.
- [x] Add a DISABLE_COLLECTSTATIC environment var with a value of one (just for initial deployment)
- [x] Add Heroku host-name (happy-little-artists.herokuapp.com) to allowed hosts in settings.py. Also add 'localhost', '127.0.0.1', '127.0.0.1:8000'.
- [x] Create a Procfile to tell Heroku to us the gunicon webserver.
- [x] Commit and push all changes, Deploy the Heroku project using GitHub.

**Comment by GaryDolan** [comment]
Initial deployment successfully carried out
