### ISSUE TITLE
USER STORY: Website Navigation 

### ISSUE THREAD

**Issue by GaryDolan** [GaryDolan/ci-p4-happy-little-artists#12]
As a **User** I can **navigate through the website with ease understanding layout and calls to action** so that **I can make use of the websites various functionality**.

# Acceptance Criteria: 
1. All navigation bar links and logo link direct the user to the correct pages.
2. Navigation bar is easy to use, intuitive and in a logical order.
3. Navigation bar uses drop down menus where appropriate.
4. Navigation bar highlights the page the user is currently on regardless of which page.
5. All calls to actions are styled consistently and stand out from page content.

# Tasks:
- [x] Create a clear and easy to use navigation menu that includes all necessary links and uses drop down menus where necessary.
- [x] Ensure a logical order giving key areas priority.
- [x] Highlight currently active page in the navigation bar.
- [x] Implement styles such as animations or color changes that provide user feedback.
- [x] Add a home link to the website headers logo/brand. 
- [x] Create calls to actions that are styled to stand out and are consistent across the website.

**Comment by GaryDolan** [comment]
Created navigation, that is easy to use, styled and responsive
