### ISSUE TITLE
USER STORY: Social network links

### ISSUE THREAD

**Issue by GaryDolan** [GaryDolan/ci-p4-happy-little-artists#13]
As a **User** I can **click on the art clubs social links in the footer** so that **I can visit the art clubs various social networks and interact with them**.

# Acceptance Criteria: 
1. Social network icons are displayed in footer and are clearly visible.
2. Social network icons are clickable and open the correct network.
3. All social networks are opened in new tabs.
4. Hover animation works correctly for all icons. 

# Tasks:
- [x] Add social network icons to the footer for Facebook, Instagram, Twitter, YouTube and LinkedIn.
- [x] Ensure the social network links are clearly viable and visually appealing.
- [x] Add hoover animation and colour change to the links in CSS.
- [x] Implement hyperlink functionality for the links, linking them to the correct social networks.
- [x] Ensure links open in a new tab.

**Comment by GaryDolan** [comment]
Header added and styled
