### ISSUE TITLE
USER STORY: Responsive design

### ISSUE THREAD

**Issue by GaryDolan** [GaryDolan/ci-p4-happy-little-artists#14]
As a **User** I can **view the website on multiple devices with different screen sizes** so that **I can have an excellent viewing experience regardless of the device I use**.

# Acceptance Criteria: 
1. Web pages scale correctly for different screen sizes including mobile, tablet and desktops.
2. All content is visible and readable at all screen sizes and is aesthetically pleasing.
3. All images scale correctly and as intended.
4. Collapsed navigation works as intended.

# Tasks:
- [x] 1. During the website design, use a mobile first approach.
- [x] 2. Use a collapsed navigation menu for smaller devices.
- [x] 3. Ensure images used are responsive using img-fluid classe where appropriate.
- [x] 4. Use bootstrap front end framework and media queries where necessary to design responsive page layouts.
- [x] 5. Ensure all page contents are readable.
- [x] 6. Ensure all pages are aesthetically pleasing.
- [x] 7. Ensure that all pages are responsive and scale from mobile to desktop.

**Comment by GaryDolan** [comment]
Website created using responsive design.
