### ISSUE TITLE
USER STORY: Website Styling

### ISSUE THREAD

**Issue by GaryDolan** [GaryDolan/ci-p4-happy-little-artists#15]
As a **Developer** I can **add styling to the website** so that **it is visually appealing to the user, easy to use and all content is accessible and readable**.

# Acceptance Criteria: 
1. The styling across the pages is consistent.
2. Page layouts are clean and easy to follow.
3. Selected colours and fonts are used across the website.
4. Images used align with the websites branding goals and target market.

# Tasks:
- [x] Use selected colour pallet when styling the web pages.
- [x] Use selected fonts when styling the web pages.
- [x] Use bootstrap to ensure the page layouts are logical and easy to follow.
- [x] Style necessary page elements with custom CSS creating a consistent style for various site elements.
- [x] Choose images appropriate to the sites branding goals (child friendly/artistic).

**Comment by GaryDolan** [comment]
All images selected for website, user profiles, posts etc.
