### ISSUE TITLE
USER STORY: Error pages

### ISSUE THREAD

**Issue by GaryDolan** [GaryDolan/ci-p4-happy-little-artists#16]
As a **Developer** I can **create custom error templates for common errors** so that **the user is provided with a safe way to return to our website if an error occurs and the website maintains a good UX**.

# Acceptance Criteria: 
1. When any of the specified errors occurs the user is automatically redirected to the custom error page.
2. All error pages contain full header and footer functionality.
3. All error pages briefly explain the error that occurred.
4. All error pages contain a button to return home.

# Tasks:
- [x] 1. Create custom HTML template for 400 error. 
- [x] 2. Create custom HTML template for 401 error.
- [x] 3. Create custom HTML template for 403 error. 
- [x] 4. Create custom HTML template for 404 error.
- [x] 5. Create custom HTML template for 500 error. 
- [x] 6. Create custom HTML template for 503 error.

**Comment by GaryDolan** [comment]
All error pages created, styled and tested
