### ISSUE TITLE
USER STORY: News Posts

### ISSUE THREAD

**Issue by GaryDolan** [GaryDolan/ci-p4-happy-little-artists#18]
As an **Admin** I can **create, read, update and delete posts** so that **I can add and manage news post on my website**.

# Acceptance Criteria: 
1. Admin user can log into Django's admin panel at website address/admin.
2. Admin can see posts under blog section in admin panel and can create, read, update and delete posts. 
3. Summernote editor is present in the create post section of the admin panel and can be used to edit content.

# Tasks:
- [x] Create a super user which can log into Django's admin panel.
- [x] Create a Django model and associated methods for a post, using the ERD for reference. 
- [x] Add the post class to admin.py panel, including all attributes, actions and functions.
- [x] Install summernote (pip3 install django-summernote) and update requirements.txt.
- [x] Add sumernote to list of installed apps in settings.py and add its URL to url.py
- [x] Update admin.py to set post entities content field to use summernote.
- [x] Make migrations for new models including a dry run (--dry-run).
- [x] Migrate changes to database, including a plan check (--plan)

**Comment by GaryDolan** [comment]
Post model and admin class added.

**Comment by GaryDolan** [comment]
Post model and admin classes added
