### ISSUE TITLE
USER STORY: Font selection

### ISSUE THREAD

**Issue by GaryDolan** [GaryDolan/ci-p4-happy-little-artists#2]
As a **developer** I can **select the websites fonts** so that **I can provide a good user experience, highlighting readability and stakeholder branding goals**.

# Acceptance Criteria: 
1. Fonts for heading and website text are selected and provide good readability and user experience.
2. Selected fonts align with the stakeholder branding goals and target market.
3. Image of font selections is stored for later use in the README file.

# Tasks:
- [x] Carry out meeting with the stakeholder (my wife Amanda) and discuss her initial ideas regarding website fonts.
- [x] Investigate possible fonts using google fonts and other websites that align with the stakeholders branding goals.
- [x] Select fonts for headings and website text, assuring they allign with the stakholders branding, target market and project goals. 
- [x] Use fontjoy to show font pairing and save an image of the finialised font selection.

**Comment by GaryDolan** [comment]
Font selections have been finalised, "Love ya like a sister" and "Raleway" fonts were selected. San Serif will be the fallback font.
