### ISSUE TITLE
USER STORY: Comment and comment control

### ISSUE THREAD

**Issue by GaryDolan** [GaryDolan/ci-p4-happy-little-artists#20]
As an **Admin** I can **approve or reject comments** so that **I can filter out any inappropriate comments**.

# Acceptance Criteria: 
1. Admin can see comments under blog section in admin panel and can create, read, update and delete  comments.
2. Comments can be selected in the admin panel and approved.

# Tasks:
- [x] Create a Django model and associated methods for a comment, using the ERD for reference. 
- [x] Add comment to admin panel by creating a comment class in admin.py.
- [x] Add actions to admin panel to change status of comments to approved or disapproved.
- [x] Make migrations for new models including a dry run (--dry-run).
- [x] Migrate changes to database, including a plan check (--plan)

**Comment by GaryDolan** [comment]
Added comment model and admin classes
