### ISSUE TITLE
USER STORY: Profile, art class, bookings admin CRUD

### ISSUE THREAD

**Issue by GaryDolan** [GaryDolan/ci-p4-happy-little-artists#21]
As an **Admin** I can **perform crud operations on user profiles, art classes and bookings** so that **I can manage any inappropriate content or where applicable delete harmful users profiles and manage art classes and bookings**. 

# Acceptance Criteria: 
1. Admin can see profile under blog section in admin panel and can create, read, update and delete profiles.
2. Admin can see art classes under blog section in admin panel and can create, read, update and delete art classes.
3. Admin can see bookings under blog section in admin panel and can create, read, update and delete bookings.

# Tasks:
- [x] Add profile to the admin panel by creating relevant classes in admin.py.
- [x] Add art class to the admin panel by creating relevant classes in admin.py.
- [x] Add bookings to the admin panel by creating relevant classes in admin.py.

**Comment by GaryDolan** [comment]
All models added to the admin panel
