### ISSUE TITLE
USER STORY: Sign up 

### ISSUE THREAD

**Issue by GaryDolan** [GaryDolan/ci-p4-happy-little-artists#23]
As a **User** I can **sign up and create an account** so that **I can login to comment on posts, like posts and make bookings**.

# Acceptance Criteria: 
1. User sign up form should be easy to use.
2. Sign up form should contain user input validation.
3. User profile should be created and associated with user.

# Tasks:
- [x] Install allauth library (pip3 install django-allauth)
- [x] Update requirements.txt
- [x] Add allauth URLS to the urls.py in the project directory.
- [x] Add allauth apps to installed apps in the settings.py file
- [x] Add site id and redirection URLS to settings.py.
- [x] Migrate changes to database, including a plan check (--plan).
- [x] Wire up nav bar link in base template for signup
- [x] Copy allauth template files to the project template folder so they can be modified.
- [x] Modify allauth template for sign up so that it suits out websites needs. 
- [x] Use allauth user_signed_up signal or Django's post_save signal to create a profile associated with the user when a new user is created. Ensure this is on delete cascade with user.

**Comment by GaryDolan** [comment]
User can create a sign in and upon creation a user profile is created for them.
