### ISSUE TITLE
USER STORY: Login

### ISSUE THREAD

**Issue by GaryDolan** [GaryDolan/ci-p4-happy-little-artists#24]
As a **User** I can **login** so that **I can access my account, view my bookings, comment and like posts etc**.

# Acceptance Criteria: 
1. Log in form is clear and easy to use.
2. User can log into their account using details the input during the sign up process.

# Tasks:
- [x] Wire up nav bar link in base template for login.
- [x] Modify allauth template for login so that it suits out websites needs.
- [x] Ensure user is redirected to home page after log in.

**Comment by GaryDolan** [comment]
Login template, imported, modified and styled
