### ISSUE TITLE
USER STORY: Delete account 

### ISSUE THREAD

**Issue by GaryDolan** [GaryDolan/ci-p4-happy-little-artists#26]
As a **User** I can **delete my account** so that **I can remove my account and associated content**.

# Acceptance Criteria: 
1. Logged in user can delete account using the button on their profile.
2. Confirmation modal appears during deletion.
3. All user related content is removed from the site.

# Tasks:
- [ ] Add a delete account button to the user profile
- [ ] Add a modal for deletion confirmation.
- [ ] Create an update profile view to handle account deletion and removal of user content.
