### ISSUE TITLE
USER STORY: View a paginated list of news posts

### ISSUE THREAD

**Issue by GaryDolan** [GaryDolan/ci-p4-happy-little-artists#28]
As a **User** I can **view a paginated list of articles in relation to club news** so that **I can choose one to read**.

# Acceptance Criteria: 
1. The club news page of the website displays a paginated list of all the blogs in order of creation and shows all relevant details of the post.
2. Each page is limited to four posts, the first of which is highlighted in a larger container.
3. All post data is rendered dynamically and correcty.

# Tasks:
- [x] Create a view for the club news list of posts
- [x] Create a club news template to render the view, showing all relevant details of each post.
- [x] Connect up the URL in blogs app urls.py.

**Comment by GaryDolan** [comment]
Added and styled club news page
