### ISSUE TITLE
USER STORY: View a post and its comments

### ISSUE THREAD

**Issue by GaryDolan** [GaryDolan/ci-p4-happy-little-artists#29]
As a **User** I can **click on a post in the list to view** so that **I can view full details and approved comments on a post, allowing me to read the post and the opinions of the community regarding the post**.

# Acceptance Criteria: 
1. Clicking on a post link opens the full post with all relevant images and details.
2. All post data is rendered dynamically and correctly.

# Tasks:
- [x] Create a view for the detailed post page.
- [x] Create a HTML template which displays the post title text, featured image, additional images and post comments.
- [x] Connect up the URL in blogs app urls.py.
- [x] Include URL in main django projects url.py
- [x] Link clickable items in the post lists to their corresponding post so that when a post link is clicked the correct post is displayed.

**Comment by GaryDolan** [comment]
Post details page complete with title, content, images, comment and like count, creator and creation date and comments
