### ISSUE TITLE
USER STORY: Wireframes

### ISSUE THREAD

**Issue by GaryDolan** [GaryDolan/ci-p4-happy-little-artists#3]
As a **developer** I can **construct wire-frames** so that **I have details of the website layout, features and style before coding begins**.

# Acceptance Criteria: 
1. Stakeholders requirements are accurately represented in the wire-frames.
2. Wire-frame review carried out with stakeholder.
3. All agreed upon changes have been made to the wire-frames and they represent stakeholders vision regarding features, layout, colour scheme and style.
4. Images of the wire-frames have been added to my documents (correctly named, using lowercase) for later use. 

# Tasks:
- [x] Carry out meeting with the stakeholder (my wife Amanda) and ascertain requirements regarding the website features, style and layout.
- [x] With stakeholder, carry out review of similar websites to gather ideas for features , layout etc.
- [x] Use balsamiq wire-frame software to create wire-frames (both mobile and desktop) for all agreed upon pages.
- [x] Review wireframes with stakeholder and action agreed upon changes.
- [x] Add images of wireframes to documents folder for later use in the README.md file.

**Comment by GaryDolan** [comment]
Wire-frames have been completes and stored for use in the README.
