### ISSUE TITLE
USER STORY: Comment on a post 

### ISSUE THREAD

**Issue by GaryDolan** [GaryDolan/ci-p4-happy-little-artists#30]
As a **User** I can **comment on a post** so that **I can share my opinion with regards to the post content**. 

# Acceptance Criteria: 
1. Comment crispy form is rendered on post view page. 
2. Comment box can be filled out and submitted with no errors.
3. Comment messages for user feedback are displayed.
4. Comment is created and awaiting approval in the admin panel.

# Tasks:
- [x] Install crispyforms library(pip3 install django-crispy-forms)
- [x] Update requirements.txt (pip3 freeze –local > requirements.txt)
- [x] Add crispy forms to the installed apps in settings.py
- [x] Add line to settings.py so that crispy used bootstrap classes for formatting.
- [x] In forms.py create a new form class for the comment
- [x] Import comment form to views.py and add it to the rendered items for postview.
- [x] Update the post detail template so that it loads crispy forms. Add the form to the html so that it is displayed.
- [x] Add a post method to the postdetails class view so that it can handle the post request and supply a variable to indicated if a comment has been made on the post page.
- [x] In the post details template use an alert to tell the user they have a comment pending approval if they have commented.

**Comment by GaryDolan** [comment]
Added user commenting on posts.
