### ISSUE TITLE
USER STORY: Testing documentation 

### ISSUE THREAD

**Issue by GaryDolan** [GaryDolan/ci-p4-happy-little-artists#35]
As a **Developer** I can **create a detailed testing file** so that **the reader can understand my testing process, any issues I encountered and how I fixed those issues**.

# Acceptance Criteria: 
1. All relevant sections have been added to the testing file.
2. All relevant subsections have been added to the the testing file.
3. Table of content is present and correctly links to each section and subsection.
4. All image/media is stored correctly in a logical file structure and follows correct lowercase naming conventions.
5. All images/media is displayed correctly in the testing file. 

# Tasks:
Add and populate all relevant sections of the testing file using markdown. Sections to be included are, 
- [x] User story testing
- [x] Automated validation testing
- [x] Manual testing
- [x] Lighthouse testing 
- [x] Responsive design testing
- [x] Bugs encountered

**Comment by GaryDolan** [comment]
Testing documentation completed
