### ISSUE TITLE
USER STORY: Automated validation  

### ISSUE THREAD

**Issue by GaryDolan** [GaryDolan/ci-p4-happy-little-artists#38]
As a **Developer** I can **carry out validation of my code** so that **I can ensure it complies to coding guidelines**.

# Acceptance Criteria: 
1. All Validators passed with no errors.

# Tasks:
- [x]  Use the W3C HTML validator to validate HTML, fixing any error which arise.
- [x]  Use the W3C CSS validator to validate the CSS, fixing any error which arise.
- [x] Use the JSHint tool to validate the JavaScript, fixing any error which arise.
- [x] Use the code institutes Pep8 linter to validate the python code, fixing any error which arise.

**Comment by GaryDolan** [comment]
Code has been validated and improvements have been made where applicable
