### ISSUE TITLE
USER STORY: Create an entity relationship diagram

### ISSUE THREAD

**Issue by GaryDolan** [GaryDolan/ci-p4-happy-little-artists#4]
As a **developer** I can **create an entity relationship diagram** so that **I can define all database entities, the information they will store and their relationship to one another**.

# Acceptance Criteria: 
1. ERD created using agreed upon features from the wire-framing stage of the project planning.
2. ERD created using Lucidchart and contains all fields, filed types and relationships.
3. ERD reviewed with stakeholders and adjusted based on review.
4. ERD documented and saved for use in the README.

# Tasks:
- [x] Create a list of all required models using  previously agreed features, decided upon during the wire-frame creations.
- [x] For each model create a list of their required fields and the filed types.
- [x] Analyse each models relationship to one another and decide upon them and their type (one to one, one to many etc.).
- [x] Use Lucidchart application to created the ERD.
- [x] Review with stakeholder and make adjustments where required.
- [x] Save image of the ERD for later use in the README file.

**Comment by GaryDolan** [comment]
ERD has been created, modified, reviewed with mentor and finalised.
