### ISSUE TITLE
USER STORY: Lighthouse testing

### ISSUE THREAD

**Issue by GaryDolan** [GaryDolan/ci-p4-happy-little-artists#40]
As a **Developer** I can **carry out lighthouse testing on all my webpages** so that **I can assess my websites performance and accessibility**.

# Acceptance Criteria: 
1. Google lighthouse was run on all pages and improvements were made to improve scores.

# Tasks:
- [x] Run lighthouse on both mobile and desktop versions of each page.
- [x] Where possible make changes to improve the scores.
- [x] Document all pages scores.

**Comment by GaryDolan** [comment]
Lighthouse testing complete. Modifications made to load images lazy, reduce size and quality of images and dynamically use CSS and JS files where possible.
