### ISSUE TITLE
USER STORY: User Profile 

### ISSUE THREAD

**Issue by GaryDolan** [GaryDolan/ci-p4-happy-little-artists#43]
As a **User** I can **view my profile page** so that **I can see my account profile content**.

# Acceptance Criteria: 
1. Profile is accessible via the nav bar link.
2. Profile displays user details, image and about me text.
3. Profile content is retrieved correctly and displayed dynamically.
4. Profile nav bar link is only available to logged in users.

# Tasks:
- [x] Create a Django model and associated methods for a profile, using the ERD for reference.
- [x] Make migrations for new models including a dry run (--dry-run).
- [x] Migrate changes to database, including a plan check (--plan)
- [x] Wire up link in nav bar for user profile page (only if logged in)
- [x] Create a user profile template.
- [x] Create a view for the user profile.
- [x] Wire up user profile URL.
- [x] Implement error handling if user info cannot be retrieved

**Comment by GaryDolan** [comment]
Profile model, view and template complete with styling
