### ISSUE TITLE
USER STORY: Edit profile

### ISSUE THREAD

**Issue by GaryDolan** [GaryDolan/ci-p4-happy-little-artists#44]
As a **User** I can **edit my profile** so that **I can control my profile contents**

# Acceptance Criteria: 
1. Edit profile button is available on user profile.
2. Edit profile button is not available on user profile if user is not logged in.
3. Clicking edit profile button will bring the user to an edit profile page.
4. Edit profile page will contain a form which is pre-populated with the users current information.
5. User can edit and submit new profile details.
6. Entered data will be validated
7. User will be returned after the edit their profile details.

# Tasks:
- [x] Add edit profile button to user profile template
- [x] Add security so that the edit button is only available if logged in and username matches profile.
- [x] Create an edit profile page which includes a crispy form and all profile fields which can be updated.
- [x] Pre populate the edit profile page with the current users profile details.
- [x] Implement a view , url and logic to update the database.
- [x] Redirect the user to there profile page on completion.

**Comment by GaryDolan** [comment]
Both edit profile and edit user info buttons added to profile page, all templates, forms, views and urls added
