### ISSUE TITLE
USER STORY: Book an art class 

### ISSUE THREAD

**Issue by GaryDolan** [GaryDolan/ci-p4-happy-little-artists#45]
As a **User** I can **make a booking for an art class** so that **I have a note of the art classes I will be attending and I reserve my place for attending the art class**.

# Acceptance Criteria: 
1. Nav bar redirects user as expected (either sign in or make booking).
2. Make a booking page renders correctly showing all correct details.
3. All form fields work correctly including validation.
4. For drop down for available classes lists all available classes and only classes after todays date. 
5. Submit form button creates a booking that is attached to the user and the selected art class.  

# Tasks:
- [x] Create a Django model and associated methods for a art class and booking, using the ERD for reference.
- [x] Add the art-class class and the booking class to admin.py panel.
- [x] Make migrations for new models including a dry run (--dry-run).
- [x] Migrate changes to database, including a plan check (--plan).
- [x] As an admin create the art classes that will be available to book.
- [x] Create a view for the make booking page. 
- [x] Create a form for the make booking page, including form validation.
- [x] Make a template for the make booking page to render the form and information.
- [x] Link the nav bar to the make booking page if logged in or the sign in page if not logged in.
- [x] Only allow booking if the max booking count for the class has not been reached.
- [x] Increment the art class booking count.
- [x] Add code to deal with errors that may occur.

**Comment by GaryDolan** [comment]
Art club bookings are completed and working as expected.
