### ISSUE TITLE
USER STORY: View, edit and delete bookings

### ISSUE THREAD

**Issue by GaryDolan** [GaryDolan/ci-p4-happy-little-artists#47]
As a **User** I can **view and delete my bookings** so that **I can control my art class bookings**.

# Acceptance Criteria: 
1. User can view their bookings on their profile page via a view bookings link in the nav bar. 
2. User can use a delete icon to remove their art class booking

# Tasks:
- [x] Update nav bar to link profile (id=bookings) to the my bookings link.
- [x] Update the view to pull all the necessary data for bookings and pass it to the template
- [x] Update template to display the booking details, along with an edit and delete icon.
- [x] Implement logic to update user booking and associated art class counts when edit is performed
- [x] Implement logic to remove the user booking both from the user an associated art class when delete is performed
- [x] Implement defensive programming via a confirmation modal. 
- [x] Decrement art class booking count if the booking is deleted.

**Comment by GaryDolan** [comment]
Bookings can now be viewed from the users profile and can be edited and deleted
