### ISSUE TITLE
USER STORY: Contact us form

### ISSUE THREAD

**Issue by GaryDolan** [GaryDolan/ci-p4-happy-little-artists#48]
As a **User** I can **fill out a contact form** so that **I can communicate with the website owner directly**.

# Acceptance Criteria: 
1. User can access a contact us page via the nav bar.
2. Contact us page is a form which the user can fill out to contact the club owner directly.
3. Contact contains relevant fields based on if the user is logged in or not. 

# Tasks:
- [x] Create contact us template and form 
- [x] Create a contact us view and add it to the URLS.
- [x] Ensure contact us template is rendered so that a logged in user is never asked for information that is already contained in the database.
- [x] Use django email service to send the users query directly to the club email address.

**Comment by GaryDolan** [comment]
Emails now send to gmail when user submits a query
