### ISSUE TITLE
USER STORY: About us page

### ISSUE THREAD

**Issue by GaryDolan** [GaryDolan/ci-p4-happy-little-artists#49]
As a **User** I can **view an about us page** so that **I can learn all about the art club, who runs it and the classes it offers**.

# Acceptance Criteria: 
1. About us page is accessible via link in nav bar.
2. About us page provides user with details regarding the Art club founder and class structure.
3. About us page contains a find use section, containing a google map to the club location.   

# Tasks:
- [x] Create an about us page template and URL 
- [x] Create an about us page view.
- [x] Add club founder and class structure sections to the about use page.
- [x] Add find us section and google map to the about us page.

**Comment by GaryDolan** [comment]
About us page complete, all elements added.
