### ISSUE TITLE
USER STORY: Home page

### ISSUE THREAD

**Issue by GaryDolan** [GaryDolan/ci-p4-happy-little-artists#50]
As a **User** I can **view a home page** so that **I can be introduced to the club and be provided with access to booking a class or reading the club news**.

# Acceptance Criteria: 
1. Home page contains a hero image with a book now button.
2. Book now button will direct the user to the booking page or the sign in page based on if the user is logged in. 
3. How page will contain a small paragraph to welcome the user. 
4. Home page will contain a club news section with cards for the 3 most recent articles.
5. Each card will contain the article heading, excerpt and a read more button linking the card to the full article. 

# Tasks:
- [x] Create a homepage template.
- [x] Add hero image and welcome text.
- [x] Create a homepage URL.
- [x] Create a homepage view to filter all posts for the most recent 3.
- [x] Link article cards to the articles and book now button to sign in/bookings based logged in status

**Comment by GaryDolan** [comment]
Home page complete including conditional nav bars and buttons
