### ISSUE TITLE
USER STORY: Messaging

### ISSUE THREAD

**Issue by GaryDolan** [GaryDolan/ci-p4-happy-little-artists#51]
As a **Developer** I can **add messaging to the website** so that **I can provide the user with feedback regarding the action they have performed**.

# Acceptance Criteria: 
1. Messages function correctly and are displayed in the correct location.
2. Messages will timeout and remove themselves from the page.

# Tasks:
- [x] In the settings.py file import messages and set up message tags.
- [x] Update base.html to display messages.
- [x] Add script with timeout function to base template to dismiss message.
Add messaging to any relevant user actions that would require them.
- [x] Creates an account
- [x] Logs into an account
- [x] Logs out of an account 
- [x] Posts a comment
- [x] Makes a booking
- [x] Deletes a booking
- [x] Liking a post 
- [x] Unliking a post 
- [x] Editing a profile

**Comment by GaryDolan** [comment]
All relevant messages have been added
