### ISSUE TITLE
USER STORY: Final deployment 

### ISSUE THREAD

**Issue by GaryDolan** [GaryDolan/ci-p4-happy-little-artists#55]
As a **Developer** I can **carry out my final deployment** so that **my website deploys correctly to Heroku**

# Acceptance Criteria: 
1. Website should look exactly as it did when running locally as we are now using the same database and the same cloudinary resources. 
2. All functionality should be the same as the local website.

# Tasks:
- [x] In env.py, set DEVELOPMENT to False so that in settings.py it will set the debug flag to FALSE.
- [x] Set x frame options so that summernote works when project is deployed.
- [x] Remove disable_collectstatic from the Heroku config vars.
- [x] Remove DEVELOPMENT from Heroku config vars, if present.
- [x] Deploy branch.
- [x] Open app to ensure it works correctly.

**Comment by GaryDolan** [comment]
Final deployment carried out
