### ISSUE TITLE
USER STORY: Store images as WEBP

### ISSUE THREAD

**Issue by GaryDolan** [GaryDolan/ci-p4-happy-little-artists#56]
As a **developer** I can **convert uploaded images to WEBP format** so that **my website has faster load time**

# Acceptance Criteria: 
1. Images can be added with no issues. 
2. Images stored in Cloudinary have been converted to WEBP.

# Tasks:
- [x] Install Django resized library (pip3 install django-resized)
- [x] Install pillow as Django resized is dependent on it.
- [x] Change img fields n models to use resizedImageField.
- [x] Add CLOUIDNARY_URL = os.environ.get('CLOUDINARY_URL') to settings.py
- [x] Make migrations for new models including a dry run (--dry-run).
- [x] Migrate changes to database, including a plan check (--plan).

**Comment by GaryDolan** [comment]
Added Django resized library and implemented .WEBP conversion for images
