### ISSUE TITLE
USER STORY: Framework and library setup

### ISSUE THREAD

**Issue by GaryDolan** [GaryDolan/ci-p4-happy-little-artists#6]
As a **Developer** I can **setup my IDE** so that **I can develop a Django based project**.

# Acceptance Criteria: 
1. Correct version of Django (3.2) installed (pip3 show django).
2. Gunicorn library has been installed (pip3 show gunicorn).
3. Correct version of dj_database_url (0.5.0) has been installed(pip3 show dj_database_url). 
4. Psycopg2 library has been installed (pip3 show psycopg2).
5. dj3-cloudinary-storage has been installed (pip3 show  dj3-cloudinary-storage).
6. Requirements.txt has been created and populated with required dependencies.

# Tasks:
- [x] Install a virtual environment in vs code.
- [x] Install Django framework (pip3 install django==3.2).
- [x] Install gunicorn server library so it can be used to run django on Heroku (pip3 install gunicorn). 
- [x] Install dj_database_url library for use with PostSQL (pip3  install dj_database_url==0.5.0).
- [x] Install psycopg2 library for use with PostSQL (pip3 install psycopg2).
- [x] Install dj3-cloudinary-storage for use with cloudinary (pip3 install dj3-cloudinary-storage).
- [x] Create a requirements.txt (pip3 freeze –local > requirements.txt).

**Comment by GaryDolan** [comment]
Virtual environment setup in VS code with all relevant installs.
