### ISSUE TITLE
USER STORY: Cloudinary setup

### ISSUE THREAD

**Issue by GaryDolan** [GaryDolan/ci-p4-happy-little-artists#8]
As a **Developer** I can **setup cloudinary** so that **my projects static and media files can be stored using the service**.

# Acceptance Criteria: 
1. Setup is complete with no errors.

# Tasks:
- [x] Setup a cloudinary account and obtain the API Environment variable.
- [x] Add the API environment variable to the env.py file as CLOUDINARY_URL.
- [x] Add cloudinary libraries to the installed apps section of the settings.py file.
- [x] Update settings.py so django will store media and static files on cloudinary.
- [x] Add folders for templates, media and static to the project root.
- [x] Add template folders to each app.
- [x] Add templates directory to settings.py and update DIRS key to point at template variable.

**Comment by GaryDolan** [comment]
Cloudinary has been setup for static and media file storage
