### ISSUE TITLE
USER STORY: Database setup

### ISSUE THREAD

**Issue by GaryDolan** [GaryDolan/ci-p4-happy-little-artists#9]
As a **Developer** I can **setup my database** so that **my data can be stored using the database**.

# Acceptance Criteria: 
1. Setup is complete with no errors. 

# Tasks:
- [x] Create a new database using ElephantSQL.com (obtain URL).
- [x] Add an environ variables for DATABASE_URL to env.py but leave commented out.
- [x] Add logic for local or production database selection to settings.py based on DATABASE_URL .

**Comment by GaryDolan** [comment]
Logic was added to select db.sqllite3 database for local use and elephant SQL database for production use.
